@startuml
'https://plantuml.com/use-case-diagram

left to right direction

skinparam usecase {
    BackgroundColor Khaki
}

skinparam actor {
    BackgroundColor Khaki
}

:Usuário: <|-- :Aluno:
:Usuário: <|-- :Professor:
:Usuário: <|-- :Administração:

rectangle "Sistema de Matrícula" {

:Administração: <-- (Realizar Matrícula)
:Administração: <-- (Cancelar Matrícula)

:Aluno: --> (Realizar Matrícula)
:Aluno: --> (Cancelar Matrícula)

:Professor: --> (Consultar Alunos Matriculados)

(Matricular em Optativa) .> (Realizar Matrícula) : <<extend>>
}

@enduml
